[package]
name = "spray_compiler_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bpaf = { version = "0.9.24", features = ["derive"]}
color-eyre = { version = "0.6.5", default-features = false }
image = { version = "0.25.10", default-features = false, features = ["default-formats"] }
itertools = "0.14.0"
lazy-regex = "3.6.0"
notify = "8.2.0"
texpresso = { version = "2.0.2", features = ["rayon"] }
walkdir = "2.5.0"

[profile.release]
debug = true