[package]
name = "source-spray-thumbnails"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
image = { workspace = true }
texture2ddecoder = { workspace = true }
thiserror = { workspace = true }
windows-core = { workspace = true }
windows = { workspace = true }
winreg = { workspace = true }