[package]
name = "source-spray-compiler-wasm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
source-spray-common = { path = "../common" }
source-spray-compiler-core = { path = "../compiler-core" }
wasm-bindgen.workspace = true
image.workspace = true
